sqlite:
  adapter: sqlite
  dbfile: nested_ajax.sqlite.db

sqlite3:
  adapter: sqlite3
  dbfile: nested_ajax.sqlite3.db

postgresql:
  adapter: postgresql
  username: postgres
  password: postgres
  database: nested_ajax_test
  min_messages: ERROR

mysql:
  adapter: mysql
  host: localhost
  username: root
  password:
  database: nested_ajax_test
